name: Stable Kali + Tailscale SSH Lab

on:
  workflow_dispatch:

jobs:
  lab:
    runs-on: ubuntu-latest

    steps:
      - name: Update system
        run: |
          sudo apt update && sudo apt upgrade -y

      - name: Install tools
        run: |
          sudo apt install -y curl nmap netcat-traditional git python3 python3-pip net-tools openssh-client

      - name: Install Tailscale (safe mode)
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale (NO systemd FIX)
        run: |
          sudo tailscaled --tun=userspace-networking --state=mem: &
          sleep 5

      - name: Connect Tailscale
        env:
          TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
        run: |
          sudo tailscale up \
            --authkey=$TAILSCALE_AUTHKEY \
            --hostname=github-lab \
            --accept-routes || true

      - name: Show IP
        run: |
          sudo tailscale ip -4 || true

      - name: Keep Alive (max GitHub limit)
        run: |
          echo "Keeping job alive..."

          END=$((SECONDS+21600)) # 6 hours max

          while [ $SECONDS -lt $END ]; do
            echo "RUNNING: $(date)"
            tailscale status || true
            sleep 60
          done